apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: msieraczkiewicz/arq-registry:latest
          name: registry
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
      restartPolicy: Always
