apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: msieraczkiewicz/arq-users:latest
          name: users
          imagePullPolicy: Always
          ports:
            - containerPort: 6701
          env:
            - name: EUREKA_SERVER
              value: http://registry:8761/eureka
      restartPolicy: Always