apiVersion: v1
kind: Service
metadata:
  name: spring-gateway
  labels:
    app: spring-gateway
spec:
  selector:
    app: spring-gateway
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
