apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-gateway
  labels:
    app: spring-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-gateway
  template:
    metadata:
      labels:
        app: spring-gateway
    spec:
      containers:
        - image: spring-gateway:latest
          name: spring-gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVER
              value: http://registry:8761/eureka
      restartPolicy: Always